### ISSUE TITLE
pynotify not needed?

### ISSUE THREAD

**Issue by Schnouki** [GratefulTony/TerminatorHostWatch#11]
Hi,

Tried to use this on my system. I'm using Arch with Terminator 1.92 and Python 3.8.3. At first the plugin could not load because of `pynotify` not being installed, but just commenting that `import` seems to have fixed it: I can use the plugin without any error.

So... is pynotify really needed? Am I missing something?

Thanks!

**Comment by owlet-labs** [comment]
pynotify was not needed. the dependency has been removed.
