### ISSUE TITLE
host_watch.py failed, terminator 1.91, Ubuntu 20.04.02 LTS

### ISSUE THREAD

**Issue by jcrodriguezu** [GratefulTony/TerminatorHostWatch#13]
Hi,

When running:
$ terminator --debug-classes=HostWatch

I get:
terminator --debug-classes=HostWatch
Traceback (most recent call last):
  File "/usr/bin/terminator", line 68, in <module>
    OPTIONS = terminatorlib.optionparse.parse_options()
  File "/usr/share/terminator/terminatorlib/optionparse.py", line 119, in parse_options
    if not options.debug > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Versions I have installed:

➜  ~ terminator -v                       
terminator 1.91

➜  ~ python3 --version  
Python 3.8.5

➜  ~ cat /etc/issue
Ubuntu 20.04.2 LTS

Any ideas on how to fix it?

Thanks

**Comment by jcrodriguezu** [comment]
Fixed

**Comment by owlet-labs** [comment]
curious as to what this was and how you resolved it
