### ISSUE TITLE
Can't seem to get the plugin to load

### ISSUE THREAD

**Issue by marcusorjames** [GratefulTony/TerminatorHostWatch#5]
Used the apt repo, the plugin .py is in the plugins location although all the other plugins seem to have a .pyc file as well.

Plugin is not appearing in the plugins tab in preferences.

**Comment by jabes** [comment]
I'm having the same issue. The plugin gets loaded with no errors:

> ConfigBase::load: ConfigBase::load: Processing section: plugins
> ConfigBase::load: ConfigBase::load: Processing plugins: HostWatch

And the `host_watch.pyc` file is created, but the plugin is not visible in the preferences pane.
I added `enabled_plugins = HostWatch,` to the config with no luck.
I'm running kernel `4.17.13-arch1-1-ARCH` and terminator `1.91`
Maybe this is an incompatibility issue?

**Comment by jabes** [comment]
I noticed the python script uses `/usr/bin/python` which happens to be python3 for me. Tried switching to python2 to see if that would help but still no luck.

**Comment by jabes** [comment]
Looking a bit closer I noticed this:

```
try:
    import pynotify
    # Every plugin you want Terminator to load *must* be listed in 'AVAILABLE'
    # This is inside this try so we only make the plugin available if pynotify
    #  is present on this computer.
    AVAILABLE = ['HostWatch']
except ImportError:
    err(_('HostWatch plugin unavailable'))
```
Looks like the plugin is not activated unless you have `pynotify` installed which I did not. Arch install: `sudo pacman -S python2-notify` or `sudo pacman -S python2-pip && pip2 install py-notify`. Unfortunately when I try to import `pynotify`, I get these errors:

> Traceback (most recent call last):
>   File "host_watch.py", line 157, in <module>
>     import pynotify
>   File "/usr/lib/python2.7/site-packages/gtk-2.0/pynotify/__init__.py", line 21, in <module>
>     from _pynotify import *
> ImportError: could not import gobject (could not find _PyGObject_API object)

I'm not sure why I'm getting this error but it seems like `pynotify` is not working on my machine for whatever reason. So for fun, I replaced the `try/catch` with simply: `AVAILABLE = ['HostWatch']`, and now the plugin shows in my preferences huzzah! However it does not appear to work at all, so I assume `pynotify` was important? When terminator tries to load the plugin I now get these errors:

> Traceback (most recent call last):
>   File "/home/justin/.config/terminator/plugins/host_watch.py", line 191, in check_host
>     last_line = self.get_last_line(terminal)
>   File "/home/justin/.config/terminator/plugins/host_watch.py", line 271, in get_last_line
>     lines=lines.splitlines()
> AttributeError: '_ResultTuple' object has no attribute 'splitlines'

> Traceback (most recent call last):
>   File "/home/justin/.config/terminator/plugins/host_watch.py", line 191, in check_host
>     last_line = self.get_last_line(terminal)
>   File "/home/justin/.config/terminator/plugins/host_watch.py", line 254, in get_last_line
>     dbg("line below prompt min size of "+str(self.prompt_minlen)+ " chars : must iterate back '"+lines+"'")
> TypeError: cannot concatenate 'str' and '_ResultTuple' objects

**Comment by owlet-labs** [comment]
This may be relevant:
https://forums.opensuse.org/showthread.php/476126-could-not-find-_PyGObject_API-object
