### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by adrienbrunet** [GratefulTony/TerminatorHostWatch#9]
Hi there, I noticed some troubles to use your plugin.

First, pynotify is required and  it fails almost silently without it. We could add a line in the README in the install section. (I can add a PR if you wish)
Second, I got some problems in the `get_last_line` function but the code on github is not the same than the one I have. Maybe I was outdated but I don't see any activity in the last 3 years. Are  releases up to date ? This problem was kind of addressed in a pending PR, see https://github.com/GratefulTony/TerminatorHostWatch/pull/6/files/3cc4b2e983f5d2d0fdac38edd50c0a461a69a307#r356445730)
Also, it could be easier for other people to give a full example of a working configuration in the documentation.

Tell me if you need any help on any of the above.

Thanks for this plugin, I had fun playin with it the last few days!

**Comment by owlet-labs** [comment]
I'll look into fixing the release. Thanks

**Comment by owlet-labs** [comment]
I have made changes, can you check if the fixes are working? I have defaulted to a manual/script-based install which brings in the newer fixes. the ppa build was out of date.

**Comment by adrienbrunet** [comment]
Thanks for those! Maybe add a line about pynotify requirement ?

**Comment by adrienbrunet** [comment]
pynotify apart, it seems to work. ;)

**Comment by owlet-labs** [comment]
Good to hear it's working. I'll look into the pynotify issue
